/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    tenants: Tenant;
    users: User;
    media: Media;
    pages: Page;
    'ita-checklist': ItaChecklist;
    'mensajes-contacto': MensajesContacto;
    noticias: Noticia;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'ita-checklist': ItaChecklistSelect<false> | ItaChecklistSelect<true>;
    'mensajes-contacto': MensajesContactoSelect<false> | MensajesContactoSelect<true>;
    noticias: NoticiasSelect<false> | NoticiasSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Entidades públicas cliente del CMS
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  nombre: string;
  /**
   * Ej: 900316215-1
   */
  nit: string;
  /**
   * Solo minúsculas, números y guiones. Ej: alcaldia-bogota
   */
  slug: string;
  activo?: boolean | null;
  /**
   * Dominio propio si aplica. Ej: www.alcaldiabogota.gov.co
   */
  dominio?: string | null;
  logo?: (number | null) | Media;
  configuracion?: {
    /**
     * Ej: #003366
     */
    colorPrimario?: string | null;
    colorSecundario?: string | null;
    fuente?: ('inter' | 'roboto' | 'open-sans') | null;
  };
  /**
   * Enlaces que aparecen en el menú principal del sitio web. Arrastra para cambiar el orden.
   */
  menuPrincipal?:
    | {
        /**
         * Ej: Servicios
         */
        etiqueta: string;
        /**
         * Ej: /servicios o https://www.otrosito.com
         */
        enlace: string;
        /**
         * Enlaces que se despliegan al pasar el mouse sobre este ítem del menú
         */
        submenu?:
          | {
              etiqueta: string;
              /**
               * Ej: /servicios/registro-mercantil
               */
              enlace: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Enlaces fijos junto al buscador.
   */
  accesosRapidos?:
    | {
        etiqueta: string;
        /**
         * Ej: /ley-de-transparencia
         */
        enlace: string;
        id?: string | null;
      }[]
    | null;
  /**
   * La barra que muestra la ruta ("Inicio › Nombre de la página") arriba del contenido, en cada página interna.
   */
  migasPan?: {
    activo?: boolean | null;
    /**
     * Ej: #0378B3
     */
    colorFondo?: string | null;
    /**
     * Ej: #FFFFFF
     */
    colorTexto?: string | null;
    /**
     * Un poco más apagado, para distinguirla del enlace.
     */
    colorTextoActual?: string | null;
    tamanoTexto?: number | null;
    negrita?: boolean | null;
  };
  menuHamburguesa?: {
    /**
     * Texto junto al ícono dentro del panel del menú. Si se deja vacío, se usa el nombre de la entidad.
     */
    titulo?: string | null;
    /**
     * Ícono junto al título dentro del panel del menú. Si se deja vacío, se usa el logo institucional.
     */
    icono?: (number | null) | Media;
  };
  footer?: {
    /**
     * Ej: 1100px
     */
    anchoMaximo?: string | null;
    /**
     * Cada sección es una banda horizontal independiente, con su propio color de fondo (ej: una banda blanca con logos de aliados, otra banda clara con accesos rápidos, y la banda principal). Se apilan en el orden en que las agregues aquí — agrega o elimina las que necesites.
     */
    secciones?:
      | {
          /**
           * Ej: #0378B3 o #FFFFFF
           */
          colorFondo?: string | null;
          /**
           * Actívalo si el fondo de esta sección es claro (blanco, gris claro), para que el texto se siga leyendo bien.
           */
          textoOscuro?: boolean | null;
          /**
           * Agrega una columna por cada bloque de contenido que quieras mostrar (por ejemplo: "Enlaces de interés", "Contáctanos", "Síguenos"). Se acomodan solas de izquierda a derecha y pasan a una nueva línea automáticamente según su ancho — no necesitas definir filas ni sumar columnas.
           */
          columnas?:
            | {
                ancho?: ('pequena' | 'mediana' | 'grande' | 'completa') | null;
                align?: ('left' | 'center' | 'right') | null;
                verticalAlign?: ('top' | 'center' | 'bottom') | null;
                /**
                 * Horizontal sirve para barras tipo "Anticorrupción | Mapa del Sitio | ..."
                 */
                direccionContenido?: ('columna' | 'fila') | null;
                children?:
                  | (
                      | {
                          /**
                           * Envuelve una parte en **doble asterisco** para ponerla en negrita. Ej: **Sede Principal:** Calle 4 # 7-37 B/ Centro, Popayán
                           */
                          contenido: string;
                          id?: string | null;
                          blockName?: string | null;
                          blockType: 'texto';
                        }
                      | {
                          contenido: string;
                          id?: string | null;
                          blockName?: string | null;
                          blockType: 'titulo';
                        }
                      | {
                          imagen: number | Media;
                          ancho?: number | null;
                          alto?: number | null;
                          /**
                           * Si la imagen debe ser clicable
                           */
                          enlace?: string | null;
                          id?: string | null;
                          blockName?: string | null;
                          blockType: 'imagen';
                        }
                      | {
                          etiqueta: string;
                          /**
                           * Ej: /servicios, https://... , tel:018000910060
                           */
                          enlace: string;
                          id?: string | null;
                          blockName?: string | null;
                          blockType: 'enlace';
                        }
                      | {
                          /**
                           * Ej: Entidades de control
                           */
                          subtitulo?: string | null;
                          enlaces?:
                            | {
                                etiqueta: string;
                                /**
                                 * Ej: /servicios, https://..., tel:018000910060
                                 */
                                enlace: string;
                                id?: string | null;
                              }[]
                            | null;
                          id?: string | null;
                          blockName?: string | null;
                          blockType: 'lista-enlaces';
                        }
                      | {
                          logos?:
                            | {
                                imagen: number | Media;
                                ancho?: number | null;
                                alto?: number | null;
                                enlace?: string | null;
                                id?: string | null;
                              }[]
                            | null;
                          id?: string | null;
                          blockName?: string | null;
                          blockType: 'logos';
                        }
                      | {
                          redes?:
                            | {
                                red: 'facebook' | 'x' | 'instagram' | 'youtube' | 'linkedin' | 'tiktok' | 'whatsapp';
                                url: string;
                                id?: string | null;
                              }[]
                            | null;
                          id?: string | null;
                          blockName?: string | null;
                          blockType: 'redes-sociales';
                        }
                      | {
                          id?: string | null;
                          blockName?: string | null;
                          blockType: 'separador';
                        }
                      | {
                          alto?: number | null;
                          id?: string | null;
                          blockName?: string | null;
                          blockType: 'espaciador';
                        }
                      | {
                          /**
                           * Se inserta tal cual en la página — úsalo con cuidado.
                           */
                          contenido: string;
                          id?: string | null;
                          blockName?: string | null;
                          blockType: 'html';
                        }
                      | {
                          orientacionContenido?: ('vertical' | 'horizontal') | null;
                          alineacion?: ('izquierda' | 'centro' | 'derecha') | null;
                          /**
                           * Ancho, entre 80 y 320.
                           */
                          tamanoCard?: number | null;
                          iconoTamano?: number | null;
                          espacio?: number | null;
                          textoTamano?: number | null;
                          textoNegrita?: boolean | null;
                          /**
                           * Ej: #003366. Vacío = usa el color institucional.
                           */
                          textoColor?: string | null;
                          modoDesplazamiento?: ('botones' | 'automatico') | null;
                          velocidadAutomatico?: number | null;
                          accesos?:
                            | {
                                /**
                                 * Busca y elige el ícono de la tarjeta (más de 1900 disponibles).
                                 */
                                icono: string;
                                titulo: string;
                                enlace: string;
                                id?: string | null;
                              }[]
                            | null;
                          id?: string | null;
                          blockName?: string | null;
                          blockType: 'accesos-rapidos';
                        }
                      | {
                          /**
                           * Ej: #FFFFFF
                           */
                          colorLienzo?: string | null;
                          espacio?: number | null;
                          direccion?: ('horizontal' | 'vertical') | null;
                          modoDesplazamiento?: ('automatico' | 'botones') | null;
                          velocidadAutomatico?: number | null;
                          imagenes?:
                            | {
                                imagen: number | Media;
                                ancho?: number | null;
                                alto?: number | null;
                                enlace?: string | null;
                                id?: string | null;
                              }[]
                            | null;
                          id?: string | null;
                          blockName?: string | null;
                          blockType: 'imagenes-slider';
                        }
                    )[]
                  | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Imágenes, documentos y archivos subidos al CMS
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Dónde se guarda físicamente el archivo (ej: media/hero/, media/galeria/). No se puede cambiar después de subir el archivo.
   */
  carpeta:
    | 'hero'
    | 'cards'
    | 'galeria'
    | 'equipo'
    | 'aliados'
    | 'testimonios'
    | 'noticias'
    | 'documentos'
    | 'tenants'
    | 'paginas'
    | 'usuarios'
    | 'general';
  /**
   * Descripción de la imagen para lectores de pantalla (WCAG)
   */
  alt: string;
  /**
   * Tenant al que pertenece este archivo
   */
  tenant?: (number | null) | Tenant;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Usuarios del panel administrativo
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  nombre: string;
  /**
   * Define qué puede hacer este usuario en el sistema
   */
  rol?: ('superadmin' | 'admin_cliente' | 'editor' | 'visualizador') | null;
  /**
   * Obligatorio para cualquier rol distinto de Super Administrador
   */
  tenant?: (number | null) | Tenant;
  /**
   * Solo aplica a los roles Editor y Visualizador — define qué puede hacer este usuario en cada módulo, dentro del tope de su rol (Visualizador nunca crea/edita/elimina; Editor nunca elimina). Checklist ITA y Clientes son exclusivos de Super Administrador, por eso no aparecen aquí. Super Administrador y Administrador Cliente siempre tienen acceso completo dentro de su alcance.
   */
  permisos?: {
    paginas?: {
      ver?: boolean | null;
      crear?: boolean | null;
      editar?: boolean | null;
      eliminar?: boolean | null;
    };
    noticias?: {
      ver?: boolean | null;
      crear?: boolean | null;
      editar?: boolean | null;
      eliminar?: boolean | null;
    };
    medios?: {
      ver?: boolean | null;
      crear?: boolean | null;
      editar?: boolean | null;
      eliminar?: boolean | null;
    };
    mensajesContacto?: {
      ver?: boolean | null;
      editar?: boolean | null;
      eliminar?: boolean | null;
    };
  };
  /**
   * Se mostrará como tu avatar en la parte superior del panel
   */
  foto?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Páginas del sitio web institucional
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  titulo: string;
  /**
   * Ej: inicio, nosotros, contratacion. Sin "/" ni espacios.
   */
  slug: string;
  /**
   * Máximo 160 caracteres. Se usa en motores de búsqueda.
   */
  descripcion?: string | null;
  /**
   * Entidad a la que pertenece esta página
   */
  tenant: number | Tenant;
  estado: 'borrador' | 'revision' | 'publicado' | 'archivado';
  /**
   * Imagen que aparece al compartir en redes. 1200x630px recomendado.
   */
  imagenSeo?: (number | null) | Media;
  /**
   * Arrastra y ordena los bloques para construir la página
   */
  layout?:
    | (
        | {
            titulo: string;
            subtitulo?: string | null;
            /**
             * Entre 20 y 90. Recomendado: 40-56.
             */
            tituloTamano?: number | null;
            tituloNegrita?: boolean | null;
            /**
             * Ej: #003366. Vacío = usa el color institucional.
             */
            tituloColor?: string | null;
            /**
             * Ej: #0066CC. Vacío = usa el color institucional.
             */
            subtituloColor?: string | null;
            /**
             * Alinea el título y el subtítulo dentro del banner.
             */
            tituloPosicion?: ('izquierda' | 'centro' | 'derecha') | null;
            /**
             * Imagen grande lado izquierdo. Recomendado: 500x550px PNG fondo transparente.
             */
            imagenPrincipal?: (number | null) | Media;
            /**
             * Qué tan transparente se ve la imagen sobre el fondo del banner.
             */
            imagenDesvanecido?: ('ninguno' | 'suave' | 'medio' | 'fuerte') | null;
            /**
             * Cómo se ajusta la imagen dentro del espacio disponible.
             */
            imagenAjuste?: ('cubrir' | 'contener' | 'original') | null;
            /**
             * Agrega las tarjetas de servicios que necesites.
             */
            servicios?:
              | {
                  /**
                   * Busca y elige el ícono que mejor represente este servicio (más de 1900 disponibles).
                   */
                  icono: string;
                  label: string;
                  href: string;
                  id?: string | null;
                }[]
              | null;
            /**
             * Agrega los banners que necesites.
             */
            banners?:
              | {
                  imagen: number | Media;
                  /**
                   * Qué tan transparente se ve la imagen del banner.
                   */
                  opacidad?: ('ninguno' | 'suave' | 'medio' | 'fuerte') | null;
                  titulo?: string | null;
                  href: string;
                  id?: string | null;
                }[]
              | null;
            /**
             * Campo anterior — usar "Imagen principal" para el nuevo diseño
             */
            imagen?: (number | null) | Media;
            alineacion?: ('izquierda' | 'centro' | 'derecha') | null;
            boton?: {
              texto?: string | null;
              url?: string | null;
              estilo?: ('primario' | 'secundario' | 'outline') | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            contenido: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            ancho?: ('normal' | 'amplio' | 'completo') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'rich-text';
          }
        | {
            titulo?: string | null;
            columnas?: ('2' | '3' | '4') | null;
            items?:
              | {
                  titulo: string;
                  descripcion?: string | null;
                  imagen?: (number | null) | Media;
                  enlace?: string | null;
                  /**
                   * Ej: 📋 o fa-file-alt
                   */
                  icono?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cards';
          }
        | {
            titulo?: string | null;
            tipo?: ('grid' | 'carrusel' | 'masonry') | null;
            /**
             * Cantidad de columnas en pantallas grandes (aplica a Grilla y Masonry)
             */
            columnas?: ('2' | '3' | '4' | '5') | null;
            imagenes?:
              | {
                  imagen: number | Media;
                  caption?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'galeria';
          }
        | {
            titulo?: string | null;
            /**
             * Ej: https://www.datos.gov.co/api/... o https://secop.gov.co/api/...
             */
            endpoint: string;
            tipoVisualizacion?: ('tabla' | 'cards' | 'lista' | 'grafica') | null;
            /**
             * Separados por coma. Ej: nombre,valor,fecha
             */
            camposVisibles?: string | null;
            limiteRegistros?: number | null;
            /**
             * JSON con headers adicionales. Ej: {"Authorization": "Bearer token"}
             */
            encabezados?:
              | {
                  [k: string]: unknown;
                }
              | unknown[]
              | string
              | number
              | boolean
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'api-externa';
          }
        | {
            /**
             * Ej: Preguntas frecuentes
             */
            titulo?: string | null;
            descripcion?: string | null;
            items?:
              | {
                  pregunta: string;
                  /**
                   * Texto de la respuesta. Se mostrará al hacer clic en la pregunta.
                   */
                  respuesta: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'accordion-faq';
          }
        | {
            /**
             * El porcentaje de cumplimiento se calcula automáticamente, no se edita aquí.
             */
            titulo?: string | null;
            descripcion?: string | null;
            /**
             * Página a donde lleva el botón "Ver más"
             */
            enlace?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ita-banner';
          }
        | {
            titulo?: string | null;
            descripcion?: string | null;
            items?:
              | {
                  /**
                   * Ej: Suministro de equipos de cómputo
                   */
                  nombre: string;
                  modalidad?:
                    | ('licitacion' | 'directa' | 'minima-cuantia' | 'seleccion-abreviada' | 'concurso-meritos')
                    | null;
                  estado: 'abierto' | 'evaluacion' | 'adjudicado' | 'cerrado';
                  fechaPublicacion?: string | null;
                  /**
                   * Ej: $ 50.000.000
                   */
                  valor?: string | null;
                  /**
                   * URL del proceso en SECOP I o SECOP II
                   */
                  enlaceSecop?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contrata';
          }
        | {
            titulo?: string | null;
            descripcion?: string | null;
            items?:
              | {
                  /**
                   * Ej: Renovación del registro mercantil
                   */
                  nombre: string;
                  descripcion?: string | null;
                  tipo?: ('virtual' | 'presencial' | 'mixto') | null;
                  /**
                   * Ej: 5 días hábiles
                   */
                  tiempoRespuesta?: string | null;
                  /**
                   * Ej: Gratuito o $ 50.000
                   */
                  costo?: string | null;
                  enlace?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'tramite';
          }
        | {
            titulo?: string | null;
            descripcion?: string | null;
            items?:
              | {
                  /**
                   * Ej: Encuesta de percepción ciudadana
                   */
                  titulo: string;
                  descripcion?: string | null;
                  tipoMecanismo?: ('pqrsd' | 'encuesta' | 'rendicion-cuentas' | 'consulta' | 'foro') | null;
                  enlace: string;
                  fechaLimite?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'participa';
          }
        | {
            titulo?: string | null;
            descripcion?: string | null;
            items?:
              | {
                  /**
                   * Ej: Empresas registradas por sector 2025
                   */
                  nombre: string;
                  descripcion?: string | null;
                  formato?: ('csv' | 'xlsx' | 'json' | 'xml' | 'pdf') | null;
                  fechaActualizacion?: string | null;
                  enlaceDescarga: string;
                  enlaceCatalogo?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'datos-abiertos';
          }
        | {
            titulo?: string | null;
            descripcion?: string | null;
            items?:
              | {
                  /**
                   * Ej: Resolución 1519 de 2020
                   */
                  nombre: string;
                  descripcion?: string | null;
                  /**
                   * Ej: Normativa, Informes, Manuales
                   */
                  categoria?: string | null;
                  archivo: number | Media;
                  fecha?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'document-list';
          }
        | {
            /**
             * Ej: Nuestra historia, Hitos del plan de desarrollo
             */
            titulo?: string | null;
            descripcion?: string | null;
            items?:
              | {
                  /**
                   * Ej: 2024 o Marzo de 2025
                   */
                  fecha: string;
                  titulo: string;
                  descripcion?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'timeline';
          }
        | {
            /**
             * Ej: Presupuesto por vigencia, Indicadores de gestión
             */
            titulo?: string | null;
            descripcion?: string | null;
            columnas?:
              | {
                  etiqueta: string;
                  id?: string | null;
                }[]
              | null;
            /**
             * Agrega una celda por cada columna definida arriba, en el mismo orden.
             */
            filas?:
              | {
                  celdas?:
                    | {
                        valor?: string | null;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'data-table';
          }
        | {
            titulo?: string | null;
            descripcion?: string | null;
            columnas?: ('2' | '3' | '4') | null;
            integrantes?:
              | {
                  foto?: (number | null) | Media;
                  nombre: string;
                  cargo: string;
                  dependencia?: string | null;
                  correo?: string | null;
                  telefono?: string | null;
                  descripcion?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'equipo';
          }
        | {
            titulo?: string | null;
            descripcion?: string | null;
            mostrarInfoContacto?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contacto';
          }
        | {
            titulo?: string | null;
            descripcion?: string | null;
            cantidad?: ('3' | '6' | '9') | null;
            soloDestacadas?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'noticias';
          }
        | {
            titulo?: string | null;
            descripcion?: string | null;
            aliados?:
              | {
                  logo: number | Media;
                  nombre: string;
                  /**
                   * Ej: https://www.aliado.com
                   */
                  enlace?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'aliados';
          }
        | {
            titulo?: string | null;
            descripcion?: string | null;
            testimonios?:
              | {
                  foto?: (number | null) | Media;
                  nombre: string;
                  cargo?: string | null;
                  testimonio: string;
                  calificacion?: ('5' | '4' | '3') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonios';
          }
        | {
            texto: string;
            /**
             * Entre 20 y 90.
             */
            textoTamano?: number | null;
            textoNegrita?: boolean | null;
            /**
             * Ej: #FFFFFF. Vacío = blanco.
             */
            textoColor?: string | null;
            textoPosicion?: ('izquierda' | 'centro' | 'derecha') | null;
            /**
             * Recomendado: 1600x400px o similar, formato horizontal.
             */
            imagenFondo?: (number | null) | Media;
            imagenDesvanecido?: ('ninguno' | 'suave' | 'medio' | 'fuerte') | null;
            imagenAjuste?: ('cubrir' | 'contener' | 'original') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'banner-pagina';
          }
        | {
            textoTamano?: number | null;
            textoNegrita?: boolean | null;
            /**
             * Ej: #FFFFFF. Vacío = blanco.
             */
            textoColor?: string | null;
            textoPosicion?: ('izquierda' | 'centro' | 'derecha') | null;
            imagenDesvanecido?: ('ninguno' | 'suave' | 'medio' | 'fuerte') | null;
            imagenAjuste?: ('cubrir' | 'contener' | 'original') | null;
            /**
             * Cada pestaña aparece como un ítem del menú lateral, con su propio banner arriba. La primera se muestra de entrada.
             */
            items?:
              | {
                  etiqueta: string;
                  bannerImagen?: (number | null) | Media;
                  /**
                   * Si se deja vacío, se usa el "Nombre en el menú".
                   */
                  bannerTexto?: string | null;
                  contenido?:
                    | (
                        | {
                            texto: string;
                            tamano?: number | null;
                            alineacion?: ('izquierda' | 'centro' | 'derecha') | null;
                            /**
                             * Vacío = usa el color institucional.
                             */
                            color?: string | null;
                            id?: string | null;
                            blockName?: string | null;
                            blockType: 'titulo';
                          }
                        | {
                            texto: string;
                            tamano?: number | null;
                            alineacion?: ('izquierda' | 'centro' | 'derecha') | null;
                            /**
                             * Vacío = usa el color institucional.
                             */
                            color?: string | null;
                            id?: string | null;
                            blockName?: string | null;
                            blockType: 'subtitulo';
                          }
                        | {
                            /**
                             * Envuelve una parte en **doble asterisco** para ponerla en negrita. Presiona Enter para hacer un salto de línea.
                             */
                            texto: string;
                            id?: string | null;
                            blockName?: string | null;
                            blockType: 'parrafo';
                          }
                        | {
                            items?:
                              | {
                                  /**
                                   * Envuelve una parte en **doble asterisco** para ponerla en negrita.
                                   */
                                  texto: string;
                                  id?: string | null;
                                }[]
                              | null;
                            id?: string | null;
                            blockName?: string | null;
                            blockType: 'vinetas';
                          }
                        | {
                            texto: string;
                            /**
                             * Busca y elige un ícono, o déjalo vacío para no mostrar ninguno.
                             */
                            icono?: string | null;
                            /**
                             * Opcional si adjuntas un documento abajo — si pones ambos, el documento tiene prioridad.
                             */
                            enlace?: string | null;
                            /**
                             * Si lo adjuntas, el botón abre este documento en una pestaña nueva en vez del enlace.
                             */
                            documento?: (number | null) | Media;
                            estilo?: ('primario' | 'secundario' | 'outline') | null;
                            /**
                             * Vacío = usa el color del estilo elegido.
                             */
                            color?: string | null;
                            redondeo?: ('ninguno' | 'suave' | 'completo') | null;
                            alineacion?: ('izquierda' | 'centro' | 'derecha') | null;
                            id?: string | null;
                            blockName?: string | null;
                            blockType: 'boton';
                          }
                        | {
                            imagen: number | Media;
                            ancho?: ('pequena' | 'mediana' | 'grande' | 'completa') | null;
                            enlace?: string | null;
                            id?: string | null;
                            blockName?: string | null;
                            blockType: 'imagen';
                          }
                        | {
                            etiqueta: string;
                            enlace: string;
                            id?: string | null;
                            blockName?: string | null;
                            blockType: 'enlace';
                          }
                        | {
                            imagen?: (number | null) | Media;
                            /**
                             * Documento, imagen o cualquier archivo que se descargará al hacer clic.
                             */
                            archivo: number | Media;
                            texto: string;
                            tamano?: number | null;
                            negrita?: boolean | null;
                            /**
                             * Vacío = usa el color institucional.
                             */
                            color?: string | null;
                            id?: string | null;
                            blockName?: string | null;
                            blockType: 'enlace-imagen';
                          }
                        | {
                            /**
                             * Busca y elige el ícono (más de 1900 disponibles).
                             */
                            icono: string;
                            texto: string;
                            id?: string | null;
                            blockName?: string | null;
                            blockType: 'icono-texto';
                          }
                        | {
                            imagenes?:
                              | {
                                  imagen: number | Media;
                                  enlace?: string | null;
                                  id?: string | null;
                                }[]
                              | null;
                            id?: string | null;
                            blockName?: string | null;
                            blockType: 'galeria';
                          }
                        | {
                            tituloTamano?: number | null;
                            tituloNegrita?: boolean | null;
                            tituloAlineacion?: ('izquierda' | 'centro' | 'derecha') | null;
                            /**
                             * Vacío = usa el color institucional.
                             */
                            tituloColor?: string | null;
                            imagenTamano?: number | null;
                            imagenAlineacion?: ('izquierda' | 'centro' | 'derecha') | null;
                            tamano?: number | null;
                            negrita?: boolean | null;
                            alineacion?: ('izquierda' | 'centro' | 'derecha') | null;
                            /**
                             * Vacío = usa el color institucional.
                             */
                            color?: string | null;
                            /**
                             * Se acomodan solos en cuadrícula — entre más agregues, más columnas ocupan.
                             */
                            elementos?:
                              | {
                                  titulo?: string | null;
                                  imagen: number | Media;
                                  texto?: string | null;
                                  enlace?: string | null;
                                  /**
                                   * Si pones ambos, el documento tiene prioridad. Se abre en una pestaña nueva.
                                   */
                                  archivo?: (number | null) | Media;
                                  id?: string | null;
                                }[]
                              | null;
                            id?: string | null;
                            blockName?: string | null;
                            blockType: 'galeria-documentos';
                          }
                        | {
                            tituloTamano?: number | null;
                            tituloNegrita?: boolean | null;
                            tituloAlineacion?: ('izquierda' | 'centro' | 'derecha') | null;
                            /**
                             * Vacío = usa el color institucional.
                             */
                            tituloColor?: string | null;
                            /**
                             * Ej: arrow-right, para la flecha de "Ver más".
                             */
                            botonIcono?: string | null;
                            /**
                             * Vacío = usa el color institucional.
                             */
                            botonColor?: string | null;
                            botonTamano?: number | null;
                            botonNegrita?: boolean | null;
                            botonAlineacion?: ('izquierda' | 'centro' | 'derecha') | null;
                            tarjetas?:
                              | {
                                  imagen: number | Media;
                                  titulo: string;
                                  textoBoton?: string | null;
                                  accion?: ('enlace' | 'modal') | null;
                                  enlace?: string | null;
                                  /**
                                   * Si se deja vacío, se usa el título de la tarjeta.
                                   */
                                  modalTitulo?: string | null;
                                  /**
                                   * Si se deja vacía, se usa la imagen de la tarjeta.
                                   */
                                  modalImagen?: (number | null) | Media;
                                  modalContenido?:
                                    | (
                                        | {
                                            texto: string;
                                            tamano?: number | null;
                                            alineacion?: ('izquierda' | 'centro' | 'derecha') | null;
                                            /**
                                             * Vacío = usa el color institucional.
                                             */
                                            color?: string | null;
                                            id?: string | null;
                                            blockName?: string | null;
                                            blockType: 'titulo';
                                          }
                                        | {
                                            texto: string;
                                            tamano?: number | null;
                                            alineacion?: ('izquierda' | 'centro' | 'derecha') | null;
                                            /**
                                             * Vacío = usa el color institucional.
                                             */
                                            color?: string | null;
                                            id?: string | null;
                                            blockName?: string | null;
                                            blockType: 'subtitulo';
                                          }
                                        | {
                                            /**
                                             * Envuelve una parte en **doble asterisco** para ponerla en negrita. Presiona Enter para hacer un salto de línea.
                                             */
                                            texto: string;
                                            id?: string | null;
                                            blockName?: string | null;
                                            blockType: 'parrafo';
                                          }
                                        | {
                                            items?:
                                              | {
                                                  /**
                                                   * Envuelve una parte en **doble asterisco** para ponerla en negrita.
                                                   */
                                                  texto: string;
                                                  id?: string | null;
                                                }[]
                                              | null;
                                            id?: string | null;
                                            blockName?: string | null;
                                            blockType: 'vinetas';
                                          }
                                        | {
                                            texto: string;
                                            /**
                                             * Busca y elige un ícono, o déjalo vacío para no mostrar ninguno.
                                             */
                                            icono?: string | null;
                                            /**
                                             * Opcional si adjuntas un documento abajo — si pones ambos, el documento tiene prioridad.
                                             */
                                            enlace?: string | null;
                                            /**
                                             * Si lo adjuntas, el botón abre este documento en una pestaña nueva en vez del enlace.
                                             */
                                            documento?: (number | null) | Media;
                                            estilo?: ('primario' | 'secundario' | 'outline') | null;
                                            /**
                                             * Vacío = usa el color del estilo elegido.
                                             */
                                            color?: string | null;
                                            redondeo?: ('ninguno' | 'suave' | 'completo') | null;
                                            alineacion?: ('izquierda' | 'centro' | 'derecha') | null;
                                            id?: string | null;
                                            blockName?: string | null;
                                            blockType: 'boton';
                                          }
                                        | {
                                            imagen: number | Media;
                                            ancho?: ('pequena' | 'mediana' | 'grande' | 'completa') | null;
                                            enlace?: string | null;
                                            id?: string | null;
                                            blockName?: string | null;
                                            blockType: 'imagen';
                                          }
                                        | {
                                            etiqueta: string;
                                            enlace: string;
                                            id?: string | null;
                                            blockName?: string | null;
                                            blockType: 'enlace';
                                          }
                                        | {
                                            imagen?: (number | null) | Media;
                                            /**
                                             * Documento, imagen o cualquier archivo que se descargará al hacer clic.
                                             */
                                            archivo: number | Media;
                                            texto: string;
                                            tamano?: number | null;
                                            negrita?: boolean | null;
                                            /**
                                             * Vacío = usa el color institucional.
                                             */
                                            color?: string | null;
                                            id?: string | null;
                                            blockName?: string | null;
                                            blockType: 'enlace-imagen';
                                          }
                                        | {
                                            /**
                                             * Busca y elige el ícono (más de 1900 disponibles).
                                             */
                                            icono: string;
                                            texto: string;
                                            id?: string | null;
                                            blockName?: string | null;
                                            blockType: 'icono-texto';
                                          }
                                        | {
                                            imagenes?:
                                              | {
                                                  imagen: number | Media;
                                                  enlace?: string | null;
                                                  id?: string | null;
                                                }[]
                                              | null;
                                            id?: string | null;
                                            blockName?: string | null;
                                            blockType: 'galeria';
                                          }
                                        | {
                                            tituloTamano?: number | null;
                                            tituloNegrita?: boolean | null;
                                            tituloAlineacion?: ('izquierda' | 'centro' | 'derecha') | null;
                                            /**
                                             * Vacío = usa el color institucional.
                                             */
                                            tituloColor?: string | null;
                                            imagenTamano?: number | null;
                                            imagenAlineacion?: ('izquierda' | 'centro' | 'derecha') | null;
                                            tamano?: number | null;
                                            negrita?: boolean | null;
                                            alineacion?: ('izquierda' | 'centro' | 'derecha') | null;
                                            /**
                                             * Vacío = usa el color institucional.
                                             */
                                            color?: string | null;
                                            /**
                                             * Se acomodan solos en cuadrícula — entre más agregues, más columnas ocupan.
                                             */
                                            elementos?:
                                              | {
                                                  titulo?: string | null;
                                                  imagen: number | Media;
                                                  texto?: string | null;
                                                  enlace?: string | null;
                                                  /**
                                                   * Si pones ambos, el documento tiene prioridad. Se abre en una pestaña nueva.
                                                   */
                                                  archivo?: (number | null) | Media;
                                                  id?: string | null;
                                                }[]
                                              | null;
                                            id?: string | null;
                                            blockName?: string | null;
                                            blockType: 'galeria-documentos';
                                          }
                                      )[]
                                    | null;
                                  id?: string | null;
                                }[]
                              | null;
                            id?: string | null;
                            blockName?: string | null;
                            blockType: 'tarjetas-imagen';
                          }
                      )[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'menu-con-contenido';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Ítems de auditoría Resolución MinTIC 1519
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ita-checklist".
 */
export interface ItaChecklist {
  id: number;
  /**
   * Número oficial del ítem en la resolución
   */
  idPregunta: number;
  categoria:
    | '1-accesibilidad'
    | '2-identidad-visual'
    | '3-informacion-entidad'
    | '4-normativa'
    | '5-contratacion'
    | '6-planeacion'
    | '7-tramites'
    | '8-participa'
    | '9-datos-abiertos'
    | '10-grupos-interes'
    | '11-reporte'
    | '12-tributaria'
    | '13-atencion-servicios'
    | '14-noticias'
    | '15-condiciones-tecnicas';
  subcategoria?: string | null;
  pregunta: string;
  /**
   * Instrucciones oficiales del MinTIC para cumplir este ítem
   */
  explicacion?: string | null;
  cumplimiento: 'si' | 'no' | 'na' | 'pendiente';
  /**
   * Justificación del estado o descripción de la evidencia
   */
  observacion?: string | null;
  /**
   * Enlace donde se puede verificar el cumplimiento
   */
  urlEvidencia?: string | null;
  fechaVerificacion?: string | null;
  /**
   * Página del sitio donde se implementa este requisito
   */
  paginaRelacionada?: (number | null) | Page;
  tenant: number | Tenant;
  updatedAt: string;
  createdAt: string;
}
/**
 * Mensajes enviados desde el formulario de contacto del sitio web
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mensajes-contacto".
 */
export interface MensajesContacto {
  id: number;
  nombre: string;
  correo: string;
  telefono?: string | null;
  asunto: string;
  mensaje: string;
  leido?: boolean | null;
  tenant: number | Tenant;
  updatedAt: string;
  createdAt: string;
}
/**
 * Noticias, avisos y comunicados publicados en el portal
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "noticias".
 */
export interface Noticia {
  id: number;
  titulo: string;
  /**
   * Ej: apertura-convocatoria-2026. Sin "/" ni espacios.
   */
  slug: string;
  /**
   * Se muestra en el listado de noticias. Máximo 200 caracteres.
   */
  resumen: string;
  contenido?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  imagen?: (number | null) | Media;
  categoria?: ('noticia' | 'aviso' | 'comunicado' | 'evento') | null;
  fechaPublicacion: string;
  destacado?: boolean | null;
  tenant: number | Tenant;
  /**
   * Debe estar en "Publicado" para que aparezca en el sitio web.
   */
  estado: 'borrador' | 'publicado';
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'ita-checklist';
        value: number | ItaChecklist;
      } | null)
    | ({
        relationTo: 'mensajes-contacto';
        value: number | MensajesContacto;
      } | null)
    | ({
        relationTo: 'noticias';
        value: number | Noticia;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  nombre?: T;
  nit?: T;
  slug?: T;
  activo?: T;
  dominio?: T;
  logo?: T;
  configuracion?:
    | T
    | {
        colorPrimario?: T;
        colorSecundario?: T;
        fuente?: T;
      };
  menuPrincipal?:
    | T
    | {
        etiqueta?: T;
        enlace?: T;
        submenu?:
          | T
          | {
              etiqueta?: T;
              enlace?: T;
              id?: T;
            };
        id?: T;
      };
  accesosRapidos?:
    | T
    | {
        etiqueta?: T;
        enlace?: T;
        id?: T;
      };
  migasPan?:
    | T
    | {
        activo?: T;
        colorFondo?: T;
        colorTexto?: T;
        colorTextoActual?: T;
        tamanoTexto?: T;
        negrita?: T;
      };
  menuHamburguesa?:
    | T
    | {
        titulo?: T;
        icono?: T;
      };
  footer?:
    | T
    | {
        anchoMaximo?: T;
        secciones?:
          | T
          | {
              colorFondo?: T;
              textoOscuro?: T;
              columnas?:
                | T
                | {
                    ancho?: T;
                    align?: T;
                    verticalAlign?: T;
                    direccionContenido?: T;
                    children?:
                      | T
                      | {
                          texto?:
                            | T
                            | {
                                contenido?: T;
                                id?: T;
                                blockName?: T;
                              };
                          titulo?:
                            | T
                            | {
                                contenido?: T;
                                id?: T;
                                blockName?: T;
                              };
                          imagen?:
                            | T
                            | {
                                imagen?: T;
                                ancho?: T;
                                alto?: T;
                                enlace?: T;
                                id?: T;
                                blockName?: T;
                              };
                          enlace?:
                            | T
                            | {
                                etiqueta?: T;
                                enlace?: T;
                                id?: T;
                                blockName?: T;
                              };
                          'lista-enlaces'?:
                            | T
                            | {
                                subtitulo?: T;
                                enlaces?:
                                  | T
                                  | {
                                      etiqueta?: T;
                                      enlace?: T;
                                      id?: T;
                                    };
                                id?: T;
                                blockName?: T;
                              };
                          logos?:
                            | T
                            | {
                                logos?:
                                  | T
                                  | {
                                      imagen?: T;
                                      ancho?: T;
                                      alto?: T;
                                      enlace?: T;
                                      id?: T;
                                    };
                                id?: T;
                                blockName?: T;
                              };
                          'redes-sociales'?:
                            | T
                            | {
                                redes?:
                                  | T
                                  | {
                                      red?: T;
                                      url?: T;
                                      id?: T;
                                    };
                                id?: T;
                                blockName?: T;
                              };
                          separador?:
                            | T
                            | {
                                id?: T;
                                blockName?: T;
                              };
                          espaciador?:
                            | T
                            | {
                                alto?: T;
                                id?: T;
                                blockName?: T;
                              };
                          html?:
                            | T
                            | {
                                contenido?: T;
                                id?: T;
                                blockName?: T;
                              };
                          'accesos-rapidos'?:
                            | T
                            | {
                                orientacionContenido?: T;
                                alineacion?: T;
                                tamanoCard?: T;
                                iconoTamano?: T;
                                espacio?: T;
                                textoTamano?: T;
                                textoNegrita?: T;
                                textoColor?: T;
                                modoDesplazamiento?: T;
                                velocidadAutomatico?: T;
                                accesos?:
                                  | T
                                  | {
                                      icono?: T;
                                      titulo?: T;
                                      enlace?: T;
                                      id?: T;
                                    };
                                id?: T;
                                blockName?: T;
                              };
                          'imagenes-slider'?:
                            | T
                            | {
                                colorLienzo?: T;
                                espacio?: T;
                                direccion?: T;
                                modoDesplazamiento?: T;
                                velocidadAutomatico?: T;
                                imagenes?:
                                  | T
                                  | {
                                      imagen?: T;
                                      ancho?: T;
                                      alto?: T;
                                      enlace?: T;
                                      id?: T;
                                    };
                                id?: T;
                                blockName?: T;
                              };
                        };
                    id?: T;
                  };
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  nombre?: T;
  rol?: T;
  tenant?: T;
  permisos?:
    | T
    | {
        paginas?:
          | T
          | {
              ver?: T;
              crear?: T;
              editar?: T;
              eliminar?: T;
            };
        noticias?:
          | T
          | {
              ver?: T;
              crear?: T;
              editar?: T;
              eliminar?: T;
            };
        medios?:
          | T
          | {
              ver?: T;
              crear?: T;
              editar?: T;
              eliminar?: T;
            };
        mensajesContacto?:
          | T
          | {
              ver?: T;
              editar?: T;
              eliminar?: T;
            };
      };
  foto?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  carpeta?: T;
  alt?: T;
  tenant?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  titulo?: T;
  slug?: T;
  descripcion?: T;
  tenant?: T;
  estado?: T;
  imagenSeo?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              titulo?: T;
              subtitulo?: T;
              tituloTamano?: T;
              tituloNegrita?: T;
              tituloColor?: T;
              subtituloColor?: T;
              tituloPosicion?: T;
              imagenPrincipal?: T;
              imagenDesvanecido?: T;
              imagenAjuste?: T;
              servicios?:
                | T
                | {
                    icono?: T;
                    label?: T;
                    href?: T;
                    id?: T;
                  };
              banners?:
                | T
                | {
                    imagen?: T;
                    opacidad?: T;
                    titulo?: T;
                    href?: T;
                    id?: T;
                  };
              imagen?: T;
              alineacion?: T;
              boton?:
                | T
                | {
                    texto?: T;
                    url?: T;
                    estilo?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'rich-text'?:
          | T
          | {
              contenido?: T;
              ancho?: T;
              id?: T;
              blockName?: T;
            };
        cards?:
          | T
          | {
              titulo?: T;
              columnas?: T;
              items?:
                | T
                | {
                    titulo?: T;
                    descripcion?: T;
                    imagen?: T;
                    enlace?: T;
                    icono?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        galeria?:
          | T
          | {
              titulo?: T;
              tipo?: T;
              columnas?: T;
              imagenes?:
                | T
                | {
                    imagen?: T;
                    caption?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'api-externa'?:
          | T
          | {
              titulo?: T;
              endpoint?: T;
              tipoVisualizacion?: T;
              camposVisibles?: T;
              limiteRegistros?: T;
              encabezados?: T;
              id?: T;
              blockName?: T;
            };
        'accordion-faq'?:
          | T
          | {
              titulo?: T;
              descripcion?: T;
              items?:
                | T
                | {
                    pregunta?: T;
                    respuesta?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'ita-banner'?:
          | T
          | {
              titulo?: T;
              descripcion?: T;
              enlace?: T;
              id?: T;
              blockName?: T;
            };
        contrata?:
          | T
          | {
              titulo?: T;
              descripcion?: T;
              items?:
                | T
                | {
                    nombre?: T;
                    modalidad?: T;
                    estado?: T;
                    fechaPublicacion?: T;
                    valor?: T;
                    enlaceSecop?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        tramite?:
          | T
          | {
              titulo?: T;
              descripcion?: T;
              items?:
                | T
                | {
                    nombre?: T;
                    descripcion?: T;
                    tipo?: T;
                    tiempoRespuesta?: T;
                    costo?: T;
                    enlace?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        participa?:
          | T
          | {
              titulo?: T;
              descripcion?: T;
              items?:
                | T
                | {
                    titulo?: T;
                    descripcion?: T;
                    tipoMecanismo?: T;
                    enlace?: T;
                    fechaLimite?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'datos-abiertos'?:
          | T
          | {
              titulo?: T;
              descripcion?: T;
              items?:
                | T
                | {
                    nombre?: T;
                    descripcion?: T;
                    formato?: T;
                    fechaActualizacion?: T;
                    enlaceDescarga?: T;
                    enlaceCatalogo?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'document-list'?:
          | T
          | {
              titulo?: T;
              descripcion?: T;
              items?:
                | T
                | {
                    nombre?: T;
                    descripcion?: T;
                    categoria?: T;
                    archivo?: T;
                    fecha?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        timeline?:
          | T
          | {
              titulo?: T;
              descripcion?: T;
              items?:
                | T
                | {
                    fecha?: T;
                    titulo?: T;
                    descripcion?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'data-table'?:
          | T
          | {
              titulo?: T;
              descripcion?: T;
              columnas?:
                | T
                | {
                    etiqueta?: T;
                    id?: T;
                  };
              filas?:
                | T
                | {
                    celdas?:
                      | T
                      | {
                          valor?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        equipo?:
          | T
          | {
              titulo?: T;
              descripcion?: T;
              columnas?: T;
              integrantes?:
                | T
                | {
                    foto?: T;
                    nombre?: T;
                    cargo?: T;
                    dependencia?: T;
                    correo?: T;
                    telefono?: T;
                    descripcion?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        contacto?:
          | T
          | {
              titulo?: T;
              descripcion?: T;
              mostrarInfoContacto?: T;
              id?: T;
              blockName?: T;
            };
        noticias?:
          | T
          | {
              titulo?: T;
              descripcion?: T;
              cantidad?: T;
              soloDestacadas?: T;
              id?: T;
              blockName?: T;
            };
        aliados?:
          | T
          | {
              titulo?: T;
              descripcion?: T;
              aliados?:
                | T
                | {
                    logo?: T;
                    nombre?: T;
                    enlace?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        testimonios?:
          | T
          | {
              titulo?: T;
              descripcion?: T;
              testimonios?:
                | T
                | {
                    foto?: T;
                    nombre?: T;
                    cargo?: T;
                    testimonio?: T;
                    calificacion?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'banner-pagina'?:
          | T
          | {
              texto?: T;
              textoTamano?: T;
              textoNegrita?: T;
              textoColor?: T;
              textoPosicion?: T;
              imagenFondo?: T;
              imagenDesvanecido?: T;
              imagenAjuste?: T;
              id?: T;
              blockName?: T;
            };
        'menu-con-contenido'?:
          | T
          | {
              textoTamano?: T;
              textoNegrita?: T;
              textoColor?: T;
              textoPosicion?: T;
              imagenDesvanecido?: T;
              imagenAjuste?: T;
              items?:
                | T
                | {
                    etiqueta?: T;
                    bannerImagen?: T;
                    bannerTexto?: T;
                    contenido?:
                      | T
                      | {
                          titulo?:
                            | T
                            | {
                                texto?: T;
                                tamano?: T;
                                alineacion?: T;
                                color?: T;
                                id?: T;
                                blockName?: T;
                              };
                          subtitulo?:
                            | T
                            | {
                                texto?: T;
                                tamano?: T;
                                alineacion?: T;
                                color?: T;
                                id?: T;
                                blockName?: T;
                              };
                          parrafo?:
                            | T
                            | {
                                texto?: T;
                                id?: T;
                                blockName?: T;
                              };
                          vinetas?:
                            | T
                            | {
                                items?:
                                  | T
                                  | {
                                      texto?: T;
                                      id?: T;
                                    };
                                id?: T;
                                blockName?: T;
                              };
                          boton?:
                            | T
                            | {
                                texto?: T;
                                icono?: T;
                                enlace?: T;
                                documento?: T;
                                estilo?: T;
                                color?: T;
                                redondeo?: T;
                                alineacion?: T;
                                id?: T;
                                blockName?: T;
                              };
                          imagen?:
                            | T
                            | {
                                imagen?: T;
                                ancho?: T;
                                enlace?: T;
                                id?: T;
                                blockName?: T;
                              };
                          enlace?:
                            | T
                            | {
                                etiqueta?: T;
                                enlace?: T;
                                id?: T;
                                blockName?: T;
                              };
                          'enlace-imagen'?:
                            | T
                            | {
                                imagen?: T;
                                archivo?: T;
                                texto?: T;
                                tamano?: T;
                                negrita?: T;
                                color?: T;
                                id?: T;
                                blockName?: T;
                              };
                          'icono-texto'?:
                            | T
                            | {
                                icono?: T;
                                texto?: T;
                                id?: T;
                                blockName?: T;
                              };
                          galeria?:
                            | T
                            | {
                                imagenes?:
                                  | T
                                  | {
                                      imagen?: T;
                                      enlace?: T;
                                      id?: T;
                                    };
                                id?: T;
                                blockName?: T;
                              };
                          'galeria-documentos'?:
                            | T
                            | {
                                tituloTamano?: T;
                                tituloNegrita?: T;
                                tituloAlineacion?: T;
                                tituloColor?: T;
                                imagenTamano?: T;
                                imagenAlineacion?: T;
                                tamano?: T;
                                negrita?: T;
                                alineacion?: T;
                                color?: T;
                                elementos?:
                                  | T
                                  | {
                                      titulo?: T;
                                      imagen?: T;
                                      texto?: T;
                                      enlace?: T;
                                      archivo?: T;
                                      id?: T;
                                    };
                                id?: T;
                                blockName?: T;
                              };
                          'tarjetas-imagen'?:
                            | T
                            | {
                                tituloTamano?: T;
                                tituloNegrita?: T;
                                tituloAlineacion?: T;
                                tituloColor?: T;
                                botonIcono?: T;
                                botonColor?: T;
                                botonTamano?: T;
                                botonNegrita?: T;
                                botonAlineacion?: T;
                                tarjetas?:
                                  | T
                                  | {
                                      imagen?: T;
                                      titulo?: T;
                                      textoBoton?: T;
                                      accion?: T;
                                      enlace?: T;
                                      modalTitulo?: T;
                                      modalImagen?: T;
                                      modalContenido?:
                                        | T
                                        | {
                                            titulo?:
                                              | T
                                              | {
                                                  texto?: T;
                                                  tamano?: T;
                                                  alineacion?: T;
                                                  color?: T;
                                                  id?: T;
                                                  blockName?: T;
                                                };
                                            subtitulo?:
                                              | T
                                              | {
                                                  texto?: T;
                                                  tamano?: T;
                                                  alineacion?: T;
                                                  color?: T;
                                                  id?: T;
                                                  blockName?: T;
                                                };
                                            parrafo?:
                                              | T
                                              | {
                                                  texto?: T;
                                                  id?: T;
                                                  blockName?: T;
                                                };
                                            vinetas?:
                                              | T
                                              | {
                                                  items?:
                                                    | T
                                                    | {
                                                        texto?: T;
                                                        id?: T;
                                                      };
                                                  id?: T;
                                                  blockName?: T;
                                                };
                                            boton?:
                                              | T
                                              | {
                                                  texto?: T;
                                                  icono?: T;
                                                  enlace?: T;
                                                  documento?: T;
                                                  estilo?: T;
                                                  color?: T;
                                                  redondeo?: T;
                                                  alineacion?: T;
                                                  id?: T;
                                                  blockName?: T;
                                                };
                                            imagen?:
                                              | T
                                              | {
                                                  imagen?: T;
                                                  ancho?: T;
                                                  enlace?: T;
                                                  id?: T;
                                                  blockName?: T;
                                                };
                                            enlace?:
                                              | T
                                              | {
                                                  etiqueta?: T;
                                                  enlace?: T;
                                                  id?: T;
                                                  blockName?: T;
                                                };
                                            'enlace-imagen'?:
                                              | T
                                              | {
                                                  imagen?: T;
                                                  archivo?: T;
                                                  texto?: T;
                                                  tamano?: T;
                                                  negrita?: T;
                                                  color?: T;
                                                  id?: T;
                                                  blockName?: T;
                                                };
                                            'icono-texto'?:
                                              | T
                                              | {
                                                  icono?: T;
                                                  texto?: T;
                                                  id?: T;
                                                  blockName?: T;
                                                };
                                            galeria?:
                                              | T
                                              | {
                                                  imagenes?:
                                                    | T
                                                    | {
                                                        imagen?: T;
                                                        enlace?: T;
                                                        id?: T;
                                                      };
                                                  id?: T;
                                                  blockName?: T;
                                                };
                                            'galeria-documentos'?:
                                              | T
                                              | {
                                                  tituloTamano?: T;
                                                  tituloNegrita?: T;
                                                  tituloAlineacion?: T;
                                                  tituloColor?: T;
                                                  imagenTamano?: T;
                                                  imagenAlineacion?: T;
                                                  tamano?: T;
                                                  negrita?: T;
                                                  alineacion?: T;
                                                  color?: T;
                                                  elementos?:
                                                    | T
                                                    | {
                                                        titulo?: T;
                                                        imagen?: T;
                                                        texto?: T;
                                                        enlace?: T;
                                                        archivo?: T;
                                                        id?: T;
                                                      };
                                                  id?: T;
                                                  blockName?: T;
                                                };
                                          };
                                      id?: T;
                                    };
                                id?: T;
                                blockName?: T;
                              };
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ita-checklist_select".
 */
export interface ItaChecklistSelect<T extends boolean = true> {
  idPregunta?: T;
  categoria?: T;
  subcategoria?: T;
  pregunta?: T;
  explicacion?: T;
  cumplimiento?: T;
  observacion?: T;
  urlEvidencia?: T;
  fechaVerificacion?: T;
  paginaRelacionada?: T;
  tenant?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mensajes-contacto_select".
 */
export interface MensajesContactoSelect<T extends boolean = true> {
  nombre?: T;
  correo?: T;
  telefono?: T;
  asunto?: T;
  mensaje?: T;
  leido?: T;
  tenant?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "noticias_select".
 */
export interface NoticiasSelect<T extends boolean = true> {
  titulo?: T;
  slug?: T;
  resumen?: T;
  contenido?: T;
  imagen?: T;
  categoria?: T;
  fechaPublicacion?: T;
  destacado?: T;
  tenant?: T;
  estado?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}