/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    tenants: Tenant;
    users: User;
    media: Media;
    pages: Page;
    'ita-checklist': ItaChecklist;
    'mensajes-contacto': MensajesContacto;
    noticias: Noticia;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'ita-checklist': ItaChecklistSelect<false> | ItaChecklistSelect<true>;
    'mensajes-contacto': MensajesContactoSelect<false> | MensajesContactoSelect<true>;
    noticias: NoticiasSelect<false> | NoticiasSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Entidades públicas cliente del CMS
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  nombre: string;
  /**
   * Ej: 900316215-1
   */
  nit: string;
  /**
   * Solo minúsculas, números y guiones. Ej: alcaldia-bogota
   */
  slug: string;
  /**
   * Dominio propio si aplica. Ej: www.alcaldiabogota.gov.co
   */
  dominio?: string | null;
  logo?: (number | null) | Media;
  configuracion?: {
    /**
     * Ej: #003366
     */
    colorPrimario?: string | null;
    colorSecundario?: string | null;
    fuente?: ('inter' | 'roboto' | 'open-sans') | null;
  };
  /**
   * Enlaces que aparecen en el menú principal del sitio web. Arrastra para cambiar el orden.
   */
  menuPrincipal?:
    | {
        /**
         * Ej: Servicios
         */
        etiqueta: string;
        /**
         * Ej: /servicios o https://www.otrosito.com
         */
        enlace: string;
        /**
         * Enlaces que se despliegan al pasar el mouse sobre este ítem del menú
         */
        submenu?:
          | {
              etiqueta: string;
              /**
               * Ej: /servicios/registro-mercantil
               */
              enlace: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  footer?: {
    direccion?: string | null;
    telefonoConmutador?: string | null;
    lineaGratuita?: string | null;
    lineaAnticorrupcion?: string | null;
    correoNotificaciones?: string | null;
    /**
     * Ej: Lunes a viernes de 8:00 a.m. a 5:00 p.m.
     */
    horarioAtencion?: string | null;
    redesSociales?:
      | {
          red: 'facebook' | 'x' | 'instagram' | 'youtube' | 'linkedin' | 'tiktok' | 'whatsapp';
          /**
           * Ej: https://www.facebook.com/tuentidad
           */
          url: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Ej: Política de privacidad, Términos y condiciones, Mapa del sitio
     */
    enlacesLegales?:
      | {
          etiqueta: string;
          /**
           * Ej: /politica-privacidad
           */
          enlace: string;
          id?: string | null;
        }[]
      | null;
  };
  activo?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Imágenes, documentos y archivos subidos al CMS
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Dónde se guarda físicamente el archivo (ej: media/hero/, media/galeria/). No se puede cambiar después de subir el archivo.
   */
  carpeta:
    | 'hero'
    | 'cards'
    | 'galeria'
    | 'equipo'
    | 'aliados'
    | 'testimonios'
    | 'noticias'
    | 'documentos'
    | 'tenants'
    | 'paginas'
    | 'usuarios'
    | 'general';
  /**
   * Descripción de la imagen para lectores de pantalla (WCAG)
   */
  alt: string;
  /**
   * Tenant al que pertenece este archivo
   */
  tenant?: (number | null) | Tenant;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Usuarios del panel administrativo
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  nombre: string;
  /**
   * Define qué puede hacer este usuario en el sistema
   */
  rol: 'superadmin' | 'admin_cliente' | 'editor' | 'visualizador';
  /**
   * No aplica para Super Administradores
   */
  tenant?: (number | null) | Tenant;
  /**
   * Se mostrará como tu avatar en la parte superior del panel
   */
  foto?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Páginas del sitio web institucional
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  titulo: string;
  /**
   * Ej: inicio, nosotros, contratacion. Sin "/" ni espacios.
   */
  slug: string;
  /**
   * Máximo 160 caracteres. Se usa en motores de búsqueda.
   */
  descripcion?: string | null;
  /**
   * Entidad a la que pertenece esta página
   */
  tenant: number | Tenant;
  estado: 'borrador' | 'revision' | 'publicado' | 'archivado';
  /**
   * Imagen que aparece al compartir en redes. 1200x630px recomendado.
   */
  imagenSeo?: (number | null) | Media;
  /**
   * Arrastra y ordena los bloques para construir la página
   */
  layout?:
    | (
        | {
            titulo: string;
            subtitulo?: string | null;
            /**
             * Imagen grande lado izquierdo. Recomendado: 500x550px PNG fondo transparente.
             */
            imagenPrincipal?: (number | null) | Media;
            /**
             * Grid de servicios (máximo 8)
             */
            servicios?:
              | {
                  icono:
                    | 'RefreshCw'
                    | 'Monitor'
                    | 'Download'
                    | 'Lightbulb'
                    | 'User'
                    | 'Megaphone'
                    | 'Search'
                    | 'Award'
                    | 'ClipboardList'
                    | 'BarChart';
                  label: string;
                  href: string;
                  id?: string | null;
                }[]
              | null;
            banners?:
              | {
                  imagen: number | Media;
                  titulo: string;
                  href: string;
                  id?: string | null;
                }[]
              | null;
            /**
             * Campo anterior — usar "Imagen principal" para el nuevo diseño
             */
            imagen?: (number | null) | Media;
            alineacion?: ('izquierda' | 'centro' | 'derecha') | null;
            boton?: {
              texto?: string | null;
              url?: string | null;
              estilo?: ('primario' | 'secundario' | 'outline') | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            contenido: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            ancho?: ('normal' | 'amplio' | 'completo') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'rich-text';
          }
        | {
            titulo?: string | null;
            columnas?: ('2' | '3' | '4') | null;
            items?:
              | {
                  titulo: string;
                  descripcion?: string | null;
                  imagen?: (number | null) | Media;
                  enlace?: string | null;
                  /**
                   * Ej: 📋 o fa-file-alt
                   */
                  icono?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cards';
          }
        | {
            titulo?: string | null;
            tipo?: ('grid' | 'carrusel' | 'masonry') | null;
            /**
             * Cantidad de columnas en pantallas grandes (aplica a Grilla y Masonry)
             */
            columnas?: ('2' | '3' | '4' | '5') | null;
            imagenes?:
              | {
                  imagen: number | Media;
                  caption?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'galeria';
          }
        | {
            titulo?: string | null;
            /**
             * Ej: https://www.datos.gov.co/api/... o https://secop.gov.co/api/...
             */
            endpoint: string;
            tipoVisualizacion?: ('tabla' | 'cards' | 'lista' | 'grafica') | null;
            /**
             * Separados por coma. Ej: nombre,valor,fecha
             */
            camposVisibles?: string | null;
            limiteRegistros?: number | null;
            /**
             * JSON con headers adicionales. Ej: {"Authorization": "Bearer token"}
             */
            encabezados?:
              | {
                  [k: string]: unknown;
                }
              | unknown[]
              | string
              | number
              | boolean
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'api-externa';
          }
        | {
            /**
             * Ej: Preguntas frecuentes
             */
            titulo?: string | null;
            descripcion?: string | null;
            items?:
              | {
                  pregunta: string;
                  /**
                   * Texto de la respuesta. Se mostrará al hacer clic en la pregunta.
                   */
                  respuesta: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'accordion-faq';
          }
        | {
            /**
             * El porcentaje de cumplimiento se calcula automáticamente, no se edita aquí.
             */
            titulo?: string | null;
            descripcion?: string | null;
            /**
             * Página a donde lleva el botón "Ver más"
             */
            enlace?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ita-banner';
          }
        | {
            titulo?: string | null;
            descripcion?: string | null;
            items?:
              | {
                  /**
                   * Ej: Suministro de equipos de cómputo
                   */
                  nombre: string;
                  modalidad?:
                    | ('licitacion' | 'directa' | 'minima-cuantia' | 'seleccion-abreviada' | 'concurso-meritos')
                    | null;
                  estado: 'abierto' | 'evaluacion' | 'adjudicado' | 'cerrado';
                  fechaPublicacion?: string | null;
                  /**
                   * Ej: $ 50.000.000
                   */
                  valor?: string | null;
                  /**
                   * URL del proceso en SECOP I o SECOP II
                   */
                  enlaceSecop?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contrata';
          }
        | {
            titulo?: string | null;
            descripcion?: string | null;
            items?:
              | {
                  /**
                   * Ej: Renovación del registro mercantil
                   */
                  nombre: string;
                  descripcion?: string | null;
                  tipo?: ('virtual' | 'presencial' | 'mixto') | null;
                  /**
                   * Ej: 5 días hábiles
                   */
                  tiempoRespuesta?: string | null;
                  /**
                   * Ej: Gratuito o $ 50.000
                   */
                  costo?: string | null;
                  enlace?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'tramite';
          }
        | {
            titulo?: string | null;
            descripcion?: string | null;
            items?:
              | {
                  /**
                   * Ej: Encuesta de percepción ciudadana
                   */
                  titulo: string;
                  descripcion?: string | null;
                  tipoMecanismo?: ('pqrsd' | 'encuesta' | 'rendicion-cuentas' | 'consulta' | 'foro') | null;
                  enlace: string;
                  fechaLimite?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'participa';
          }
        | {
            titulo?: string | null;
            descripcion?: string | null;
            items?:
              | {
                  /**
                   * Ej: Empresas registradas por sector 2025
                   */
                  nombre: string;
                  descripcion?: string | null;
                  formato?: ('csv' | 'xlsx' | 'json' | 'xml' | 'pdf') | null;
                  fechaActualizacion?: string | null;
                  enlaceDescarga: string;
                  enlaceCatalogo?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'datos-abiertos';
          }
        | {
            titulo?: string | null;
            descripcion?: string | null;
            items?:
              | {
                  /**
                   * Ej: Resolución 1519 de 2020
                   */
                  nombre: string;
                  descripcion?: string | null;
                  /**
                   * Ej: Normativa, Informes, Manuales
                   */
                  categoria?: string | null;
                  archivo: number | Media;
                  fecha?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'document-list';
          }
        | {
            /**
             * Ej: Nuestra historia, Hitos del plan de desarrollo
             */
            titulo?: string | null;
            descripcion?: string | null;
            items?:
              | {
                  /**
                   * Ej: 2024 o Marzo de 2025
                   */
                  fecha: string;
                  titulo: string;
                  descripcion?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'timeline';
          }
        | {
            /**
             * Ej: Presupuesto por vigencia, Indicadores de gestión
             */
            titulo?: string | null;
            descripcion?: string | null;
            columnas?:
              | {
                  etiqueta: string;
                  id?: string | null;
                }[]
              | null;
            /**
             * Agrega una celda por cada columna definida arriba, en el mismo orden.
             */
            filas?:
              | {
                  celdas?:
                    | {
                        valor?: string | null;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'data-table';
          }
        | {
            titulo?: string | null;
            descripcion?: string | null;
            columnas?: ('2' | '3' | '4') | null;
            integrantes?:
              | {
                  foto?: (number | null) | Media;
                  nombre: string;
                  cargo: string;
                  dependencia?: string | null;
                  correo?: string | null;
                  telefono?: string | null;
                  descripcion?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'equipo';
          }
        | {
            titulo?: string | null;
            descripcion?: string | null;
            mostrarInfoContacto?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contacto';
          }
        | {
            titulo?: string | null;
            descripcion?: string | null;
            cantidad?: ('3' | '6' | '9') | null;
            soloDestacadas?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'noticias';
          }
        | {
            titulo?: string | null;
            descripcion?: string | null;
            aliados?:
              | {
                  logo: number | Media;
                  nombre: string;
                  /**
                   * Ej: https://www.aliado.com
                   */
                  enlace?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'aliados';
          }
        | {
            titulo?: string | null;
            descripcion?: string | null;
            testimonios?:
              | {
                  foto?: (number | null) | Media;
                  nombre: string;
                  cargo?: string | null;
                  testimonio: string;
                  calificacion?: ('5' | '4' | '3') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonios';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Ítems de auditoría Resolución MinTIC 1519
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ita-checklist".
 */
export interface ItaChecklist {
  id: number;
  /**
   * Número oficial del ítem en la resolución
   */
  idPregunta: number;
  categoria:
    | '1-accesibilidad'
    | '2-identidad-visual'
    | '3-informacion-entidad'
    | '4-normativa'
    | '5-contratacion'
    | '6-planeacion'
    | '7-tramites'
    | '8-participa'
    | '9-datos-abiertos'
    | '10-grupos-interes'
    | '11-reporte'
    | '12-tributaria'
    | '13-atencion-servicios'
    | '14-noticias'
    | '15-condiciones-tecnicas';
  subcategoria?: string | null;
  pregunta: string;
  /**
   * Instrucciones oficiales del MinTIC para cumplir este ítem
   */
  explicacion?: string | null;
  cumplimiento: 'si' | 'no' | 'na' | 'pendiente';
  /**
   * Justificación del estado o descripción de la evidencia
   */
  observacion?: string | null;
  /**
   * Enlace donde se puede verificar el cumplimiento
   */
  urlEvidencia?: string | null;
  fechaVerificacion?: string | null;
  /**
   * Página del sitio donde se implementa este requisito
   */
  paginaRelacionada?: (number | null) | Page;
  tenant: number | Tenant;
  updatedAt: string;
  createdAt: string;
}
/**
 * Mensajes enviados desde el formulario de contacto del sitio web
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mensajes-contacto".
 */
export interface MensajesContacto {
  id: number;
  nombre: string;
  correo: string;
  telefono?: string | null;
  asunto: string;
  mensaje: string;
  leido?: boolean | null;
  tenant: number | Tenant;
  updatedAt: string;
  createdAt: string;
}
/**
 * Noticias, avisos y comunicados publicados en el portal
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "noticias".
 */
export interface Noticia {
  id: number;
  titulo: string;
  /**
   * Ej: apertura-convocatoria-2026. Sin "/" ni espacios.
   */
  slug: string;
  /**
   * Se muestra en el listado de noticias. Máximo 200 caracteres.
   */
  resumen: string;
  contenido?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  imagen?: (number | null) | Media;
  categoria?: ('noticia' | 'aviso' | 'comunicado' | 'evento') | null;
  fechaPublicacion: string;
  destacado?: boolean | null;
  tenant: number | Tenant;
  /**
   * Debe estar en "Publicado" para que aparezca en el sitio web.
   */
  estado: 'borrador' | 'publicado';
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'ita-checklist';
        value: number | ItaChecklist;
      } | null)
    | ({
        relationTo: 'mensajes-contacto';
        value: number | MensajesContacto;
      } | null)
    | ({
        relationTo: 'noticias';
        value: number | Noticia;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  nombre?: T;
  nit?: T;
  slug?: T;
  dominio?: T;
  logo?: T;
  configuracion?:
    | T
    | {
        colorPrimario?: T;
        colorSecundario?: T;
        fuente?: T;
      };
  menuPrincipal?:
    | T
    | {
        etiqueta?: T;
        enlace?: T;
        submenu?:
          | T
          | {
              etiqueta?: T;
              enlace?: T;
              id?: T;
            };
        id?: T;
      };
  footer?:
    | T
    | {
        direccion?: T;
        telefonoConmutador?: T;
        lineaGratuita?: T;
        lineaAnticorrupcion?: T;
        correoNotificaciones?: T;
        horarioAtencion?: T;
        redesSociales?:
          | T
          | {
              red?: T;
              url?: T;
              id?: T;
            };
        enlacesLegales?:
          | T
          | {
              etiqueta?: T;
              enlace?: T;
              id?: T;
            };
      };
  activo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  nombre?: T;
  rol?: T;
  tenant?: T;
  foto?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  carpeta?: T;
  alt?: T;
  tenant?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  titulo?: T;
  slug?: T;
  descripcion?: T;
  tenant?: T;
  estado?: T;
  imagenSeo?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              titulo?: T;
              subtitulo?: T;
              imagenPrincipal?: T;
              servicios?:
                | T
                | {
                    icono?: T;
                    label?: T;
                    href?: T;
                    id?: T;
                  };
              banners?:
                | T
                | {
                    imagen?: T;
                    titulo?: T;
                    href?: T;
                    id?: T;
                  };
              imagen?: T;
              alineacion?: T;
              boton?:
                | T
                | {
                    texto?: T;
                    url?: T;
                    estilo?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'rich-text'?:
          | T
          | {
              contenido?: T;
              ancho?: T;
              id?: T;
              blockName?: T;
            };
        cards?:
          | T
          | {
              titulo?: T;
              columnas?: T;
              items?:
                | T
                | {
                    titulo?: T;
                    descripcion?: T;
                    imagen?: T;
                    enlace?: T;
                    icono?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        galeria?:
          | T
          | {
              titulo?: T;
              tipo?: T;
              columnas?: T;
              imagenes?:
                | T
                | {
                    imagen?: T;
                    caption?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'api-externa'?:
          | T
          | {
              titulo?: T;
              endpoint?: T;
              tipoVisualizacion?: T;
              camposVisibles?: T;
              limiteRegistros?: T;
              encabezados?: T;
              id?: T;
              blockName?: T;
            };
        'accordion-faq'?:
          | T
          | {
              titulo?: T;
              descripcion?: T;
              items?:
                | T
                | {
                    pregunta?: T;
                    respuesta?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'ita-banner'?:
          | T
          | {
              titulo?: T;
              descripcion?: T;
              enlace?: T;
              id?: T;
              blockName?: T;
            };
        contrata?:
          | T
          | {
              titulo?: T;
              descripcion?: T;
              items?:
                | T
                | {
                    nombre?: T;
                    modalidad?: T;
                    estado?: T;
                    fechaPublicacion?: T;
                    valor?: T;
                    enlaceSecop?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        tramite?:
          | T
          | {
              titulo?: T;
              descripcion?: T;
              items?:
                | T
                | {
                    nombre?: T;
                    descripcion?: T;
                    tipo?: T;
                    tiempoRespuesta?: T;
                    costo?: T;
                    enlace?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        participa?:
          | T
          | {
              titulo?: T;
              descripcion?: T;
              items?:
                | T
                | {
                    titulo?: T;
                    descripcion?: T;
                    tipoMecanismo?: T;
                    enlace?: T;
                    fechaLimite?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'datos-abiertos'?:
          | T
          | {
              titulo?: T;
              descripcion?: T;
              items?:
                | T
                | {
                    nombre?: T;
                    descripcion?: T;
                    formato?: T;
                    fechaActualizacion?: T;
                    enlaceDescarga?: T;
                    enlaceCatalogo?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'document-list'?:
          | T
          | {
              titulo?: T;
              descripcion?: T;
              items?:
                | T
                | {
                    nombre?: T;
                    descripcion?: T;
                    categoria?: T;
                    archivo?: T;
                    fecha?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        timeline?:
          | T
          | {
              titulo?: T;
              descripcion?: T;
              items?:
                | T
                | {
                    fecha?: T;
                    titulo?: T;
                    descripcion?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'data-table'?:
          | T
          | {
              titulo?: T;
              descripcion?: T;
              columnas?:
                | T
                | {
                    etiqueta?: T;
                    id?: T;
                  };
              filas?:
                | T
                | {
                    celdas?:
                      | T
                      | {
                          valor?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        equipo?:
          | T
          | {
              titulo?: T;
              descripcion?: T;
              columnas?: T;
              integrantes?:
                | T
                | {
                    foto?: T;
                    nombre?: T;
                    cargo?: T;
                    dependencia?: T;
                    correo?: T;
                    telefono?: T;
                    descripcion?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        contacto?:
          | T
          | {
              titulo?: T;
              descripcion?: T;
              mostrarInfoContacto?: T;
              id?: T;
              blockName?: T;
            };
        noticias?:
          | T
          | {
              titulo?: T;
              descripcion?: T;
              cantidad?: T;
              soloDestacadas?: T;
              id?: T;
              blockName?: T;
            };
        aliados?:
          | T
          | {
              titulo?: T;
              descripcion?: T;
              aliados?:
                | T
                | {
                    logo?: T;
                    nombre?: T;
                    enlace?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        testimonios?:
          | T
          | {
              titulo?: T;
              descripcion?: T;
              testimonios?:
                | T
                | {
                    foto?: T;
                    nombre?: T;
                    cargo?: T;
                    testimonio?: T;
                    calificacion?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ita-checklist_select".
 */
export interface ItaChecklistSelect<T extends boolean = true> {
  idPregunta?: T;
  categoria?: T;
  subcategoria?: T;
  pregunta?: T;
  explicacion?: T;
  cumplimiento?: T;
  observacion?: T;
  urlEvidencia?: T;
  fechaVerificacion?: T;
  paginaRelacionada?: T;
  tenant?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mensajes-contacto_select".
 */
export interface MensajesContactoSelect<T extends boolean = true> {
  nombre?: T;
  correo?: T;
  telefono?: T;
  asunto?: T;
  mensaje?: T;
  leido?: T;
  tenant?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "noticias_select".
 */
export interface NoticiasSelect<T extends boolean = true> {
  titulo?: T;
  slug?: T;
  resumen?: T;
  contenido?: T;
  imagen?: T;
  categoria?: T;
  fechaPublicacion?: T;
  destacado?: T;
  tenant?: T;
  estado?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}